[tool.black]
line-length = 100
target-version = ['py312']
skip-string-normalization = false

[tool.isort]
profile = "black"  # ensures consistency with Black

[flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]  # ignore rules that conflict with Black