# Generated by Django 5.2.7 on 2025-10-05 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="planned_times",
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="actual_time",
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="planned_time",
        ),
        migrations.AddField(
            model_name="tracker",
            name="actual_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="actual_starttime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="planned_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="planned_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[("study_daily", "Study Daily"), ("study_hours", "Study Hours")],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="15 for 15th of the month", null=True
                    ),
                ),
                (
                    "week_order",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="2 for 2nd Wednesday of the month", null=True
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("once", "Once"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="tracker_app.goal",
                    ),
                ),
            ],
        ),
    ]
