# Generated by Django 5.2.7 on 2025-10-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0002_remove_goal_planned_times_remove_tracker_actual_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("done", "Done"),
                    ("partial", "Partial"),
                    ("skipped", "Skipped"),
                ],
                default="planned",
            ),
        ),
    ]
