# Generated by Django 5.2.7 on 2025-10-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0003_tracker_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ],
                help_text="The month (1-12).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tracker",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trackers",
                to="tracker_app.schedule",
            ),
        ),
    ]
