# Generated by Django 5.2.7 on 2025-10-07 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0004_schedule_month_tracker_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="day",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="month",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="recurrence",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="week_order",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="weekday",
        ),
        migrations.AddField(
            model_name="schedule",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
