# Generated by Django 5.2.7 on 2025-10-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0005_remove_schedule_day_remove_schedule_month_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracker",
            old_name="actual_starttime",
            new_name="actual_start_time",
        ),
    ]
