# Generated by Django 5.2.7 on 2025-10-09 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0006_rename_actual_starttime_tracker_actual_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="description",
            field=models.TextField(
                blank=True, help_text="What exactly must be achieved", null=True
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="goal_context",
            field=models.JSONField(
                blank=True,
                help_text="Per-day plan toward the goal (e.g., planned_hours, topic).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tracker",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="description",
            field=models.TextField(
                blank=True, help_text="What exactly must be/was achieved", null=True
            ),
        ),
        migrations.CreateModel(
            name="DomainReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("quarter", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("reflections", models.TextField(blank=True, null=True)),
                ("summary_progress", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tracker_app.domain",
                    ),
                ),
            ],
            options={
                "unique_together": {("domain", "year", "month", "week", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="GoalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("reflections", models.TextField(blank=True, null=True)),
                ("overall_progress", models.FloatField(default=0)),
                ("carry_over_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="tracker_app.goal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="daily",
                        help_text="How often the schedule repeats (daily/weekly/monthly).",
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Repeat every N units (days/weeks/months)."
                    ),
                ),
                ("weekdays", models.JSONField(blank=True, default=list)),
                (
                    "days",
                    models.JSONField(
                        blank=True, default=list, help_text="Specific days of the month."
                    ),
                ),
                (
                    "week_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional: nth weekdays for monthly recurrence.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What exactly must be achieved for this recurring block.",
                        null=True,
                    ),
                ),
                (
                    "goal_context",
                    models.JSONField(
                        blank=True,
                        help_text="Default goal-specific context for generated schedules (e.g. planned_hours, topic).",
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("exceptions", models.JSONField(blank=True, default=list)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to="tracker_app.goal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="tracker_app.schedulerule",
            ),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
